/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as datasetErc20Sol from "./DatasetERC20.sol";
export type { datasetErc20Sol };
export type { DatasetOwnership } from "./DatasetOwnership";
