/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as datasetErc20Sol from "./DatasetERC20.sol";
export { DatasetOwnership__factory } from "./DatasetOwnership__factory";
